### ISSUE TITLE
该软件包在RTT下编译出现找不到cpu_ops.o错误

### ISSUE THREAD

**Issue by liqiwenx** [RT-Thread-packages/kendryte-k210-sdk#1]
该软件包在RTT下能编译出现错误:

`scons: *** [build\packages\K210-SDK-latest\lib\nncase\runtime\cpu\cpu_ops.o] Source `packages\K210-SDK-latest\lib\nncase\runtime\cpu\cpu_ops.cpp' not found, needed by target `build\packages\K210-SDK-latest\lib\nncase\runtime\cpu\cpu_ops.o'.
scons: building terminated because of errors.`

应该是Scons脚本路径包含不正确.

![image](https://user-images.githubusercontent.com/52438879/181465379-bc7c8339-877c-458d-9f00-b576941b63be.png)

并且legacy版本路径存在问题:

![image](https://user-images.githubusercontent.com/52438879/181471721-142042ee-7590-4c52-9d4a-c96f2b5dd15a.png)

**Comment by mysterywolf** [comment]
请等一下，这个新版本的SDK还没有调试完成

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread-packages/kendryte-k210-sdk/commit/50bf8c4d1534c18b7e42481e2e5933e1f2aca3dd
已经修复了 预计今天早上你就可以正确使用了，如果还有问题情报告
